### PR TITLE
SIP-30: Concentrating staking revenues

### PR DESCRIPTION
**Pull request by john-light**
Current draft for `SIP-30: Concentrating staking revenues`.

### 🗣 Comment on the current draft [here](https://github.com/DistributedCollective/SIPS/pull/30/files).
- If you comment on a line that already has a comment thread, please start a new comment thread unless your comment is relevant to the existing thread.
- You can share general comments or questions as a response below.  
- There is a thread in the Sovryn forum that you can also use to share your comments [here](https://forum.sovryn.app/t/draft-sip-30-concentrating-staking-revenues/1675/2).

### CODE REVIEW

**Comment by bitnym** [comment]
I'm heartened to see this long overdue proposal. I believe it should include a more detailed description of the several staked SOV tranches. A brief summary of the token distribution cycle, vesting schedules, would go a long way toward voters understanding better the implications of the vote and who it affects the most (i.e., it gives early investors a chance to earn a little before their stake is eclipsed by the team members vesting schedules). A rough estimate of current distribution weight by type (team, genesis sale, origins sale, etc.) would be useful.

For example, a casual analysis of past votes shows a few (less than 10) addresses control over 90% of the voting weight (excluding the delegated).

I also think a brief explanation or link to how the fee split is weighted would be helpful (as I understand it, it's the same metric used for voting weight).

Also, just to put it out there, SIP-030 does not change the voting weight allocation, i.e., team members and others with unvested SOV still maintain their original voting power.

**Comment by john-light** [comment]
Thank you for your comments @bitnym!

>  I believe it should include a more detailed description of the several staked SOV tranches.

I did publish some info about this on the forum, I can update the SIP to include it:

https://forum.sovryn.app/t/draft-sip-30-concentrating-staking-revenues/1675/5

> A rough estimate of current distribution weight by type (team, genesis sale, origins sale, etc.) would be useful.
> 
> For example, a casual analysis of past votes shows a few (less than 10) addresses control over 90% of the voting weight (excluding the delegated).

Myself and the devs I work with are pretty maxed out right now, speaking for myself I do not have time to do this and I don't think anyone else I work with does either. However if you or anyone else wants to run these numbers and share them, I do think they would be great to further illustrate the effects of this proposal for SOV stakers and I'd be happy to update the SIP to include them.

> I also think a brief explanation or link to how the fee split is weighted would be helpful (as I understand it, it's the same metric used for voting weight).
> Also, just to put it out there, SIP-030 does not change the voting weight allocation, i.e., team members and others with unvested SOV still maintain their original voting power.

Yes fees are currently split pro rata based on voting power. And as you point out, staked SOV that is currently encumbered by vesting contracts does get full voting power. (Terminology-wise, I think the better term for this is "locking" rather than "vesting", since typically, only fully-vested assets get full voting rights. Something to think about as we go forward - but I digress.)

**Comment by CarCry** [comment]
Were staking rewards only for fully vested (unlocked) Sov from SIP-024

**Comment by john-light** [comment]
@CarCry 

> Weren't staking rewards only for fully vested (unlocked) Sov from SIP-024, I think this was already given...

[SIP-0024](https://github.com/DistributedCollective/SIPS/blob/main/SIP-0024.md) introduced a new type of staking reward: SOV subsidies, distributed by the Exchequer Committee from the Adoption Fund.

In contrast, this SIP applies to all revenues that get sent to the fee proxy contract, including (and in large part) revenues derived from protocol fees, such as loan origination fees and (if [SIP-0031](https://github.com/DistributedCollective/SIPS/pull/31) is approved) AMM swap fees.

**Pull request merged**
